name: PR

on: 
  pull_request:
    types: [opened]


jobs:
  fetch_pr_number:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get_pr_number.outputs.pr_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR Number
        id: get_pr_number
        run: |
          USER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          echo "USER: $USER"

          # Fetch PRs using curl
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=$USER:${{ github.head_ref || github.ref_name }}")

          # Extract PR number using jq
          PR_NUMBER=$(echo "$response" | jq '.[0].number')

          # Set the PR number as an output
          echo "PR_NUMBER: $PR_NUMBER"
          echo "::set-output name=pr_number::$PR_NUMBER"

  comment-pull-request:
    runs-on: ubuntu-latest
    needs: 
      - fetch_pr_number
    if: needs.fetch_pr_number.outputs.pr_number != 'null'
    name: A job to generate comment based on code coverage

    steps:
      - name: Code coverage action step
        id: code_coverage
        uses: wesfdev/my-cc-g-action@v1.14
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSHED_GITHUB_SHA: ${{ github.event.pull_request.head.sha || github.sha}}
          GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_URL: ${{ secrets.COVERALLS_URL }}
          PR_NUMBER: ${{ needs.fetch_pr_number.outputs.pr_number }}
