name: PR

on: 
  pull_request:
    types: [opened]

env:
  MIX_ENV: test
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  COVERALLS_URL: ${{ secrets.COVERALLS_URL }}

jobs:
  comment-pull-request:
    needs: run-tests
    runs-on: ubuntu-latest
    name: A job to generate comment based on code coverage
    steps:
      - name: Code coverage action step
        id: code_coverage
        uses: wesfdev/my-cc-g-action@v1.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}