name: PR

on: 
  pull_request:
    types: [opened]

jobs:
  comment-pull-request:
    runs-on: ubuntu-latest
    name: A job to generate comment based on code coverage
    steps:
      - name: Code coverage action step
        id: code_coverage
        uses: wesfdev/my-cc-g-action@v1.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSHED_GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_URL: ${{ secrets.COVERALLS_URL }}